language: node_js
node_js:
  - 14


jobs:
  include:
    - stage: build common module
      script:
        - cd udagram-common
        - npm version 0.0.$TRAVIS_BUILD_NUMBER
        - npm install
        - npm run lint
        - npm run build
        - npm publish
    - stage: build users api
      before_script:
        - export BUILD_DIR=udagram-users-api
      script:
        - cd $BUILD_DIR
        - npm install
        - npm run lint
        - npm run build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/$BUILD_DIR:$TRAVIS_BUILD_NUMBER .
        - docker push $DOCKER_USERNAME/$BUILD_DIR:$TRAVIS_BUILD_NUMBER

    